### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by bpg-it-raphaeljohn** [horizon3ai/vcenter_saml_login#15]
Hello, I would like to contribute to the code adding a more reliable validation for keys and certs, but there is no license in this repository.
Please add some sort auf license to the repository. No license generally means you have no permission from the creators of the software to use, modify, or share the software. More info here [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/)

**Comment by scopedsecurity** [comment]
Hello! Thanks for bringing this up - I've added the MIT license to the project. Contributions to the project are welcome and those are some great ideas for improving the project!

Let me know if you have any more questions.
