### ISSUE TITLE
 An error occurred

### ISSUE THREAD

**Issue by Hosrg** [horizon3ai/vcenter_saml_login#2]
Hello, I can't execute python. It may be caused by the certificate. I need help.

python3 vcenter_saml_login.py -p data.mdb -t 172.31.0.10
[*] Successfully extracted the IdP certificate
[-] Failed to find the trusted certificate 1
Traceback (most recent call last):
  File "vcenter_saml_login.py", line 295, in <module>
    trusted_cert_1, domain = get_trusted_cert1(bin_stream, args.verbose)
TypeError: cannot unpack non-iterable NoneType object

**Comment by scopedsecurity** [comment]
Hello,

Can you give me any more details about the version of vCenter you are looking at?

I've pushed an update to the repo that will provide some more debugging if you provide the --verbose flag.

If you re-run with that flag and let me know the output I can help better.

**Comment by Hosrg** [comment]
Hello, 
thank you very much for answering my question, and I will continue to get errors after getting the update again.
Vm version: vmware-cm-6.7.0

python3 vcenter_saml_login.py -p data.mdb -t 172.31.0.10 -v

[!] Looking for cert 1 at position: 6819768
[!] Domain begin position: 6820192
[!] Domain end position: 6820272
[!] Domain: test.vm
[!] Cert 1 size: 12336
[!] Cert does not contain VMware Engineering - keep looking
Traceback (most recent call last):
  File "vcenter_saml_login.py", line 311, in <module>
    trusted_cert_1, domain = get_trusted_cert1(bin_stream, args.verbose)
TypeError: cannot unpack non-iterable NoneType object

**Comment by Pretexts** [comment]
Hello,
thank you very much for answering my question,I'm having the same problem.

[*] Successfully extracted the IdP certificate
[!] Looking for cert 1 at position: 7391120
[!] Domain begin position: 7440416
[!] Domain end position: 7440480
[!] Domain: vcenter
[!] Cert 1 size: 25144
[!] Cert does not contain VMware Engineering - keep looking
Traceback (most recent call last):
  File "vcenter_saml_login.py", line 311, in <module>
    trusted_cert_1, domain = get_trusted_cert1(bin_stream, args.verbose)
TypeError: cannot unpack non-iterable NoneType object

**Comment by Pretexts** [comment]
Hello,


[*] Successfully extracted the IdP certificate
[*] Successfully extracted trusted certificate 1
[*] Successfully extracted trusted certificate 2
[*] Obtaining hostname from vCenter SSL certificate
[*] Found hostname VMware default certificate for 192.168.44.121
[*] Initiating SAML request with 192.168.44.121
[-] Failed initiating SAML request with 192.168.44.121
Traceback (most recent call last):
  File "vcenter_saml_login.py", line 261, in <module>
    req = saml_request(args.target)
  File "vcenter_saml_login.py", line 159, in saml_request
    raise Exception("expected 302 redirect")
Exception: expected 302 redirect

**Comment by scopedsecurity** [comment]
Hello, I have a feeling that there could be something different about your versions than vCenter versions I've seen. It will be pretty difficult to debug without the data.mdb file. If this is a test instance, you can email me the data.mdb file at zach@horizon3.ai and I will figure it out. Otherwise, I recommend looking into the certificates that they are parsing and ensuring the data looks like it is an actual certificate.

**Comment by local-uan** [comment]
Hello,
I'm having the same problem

edition：VMware vCenter Server 7.0.2.00200

python3 vcenter_saml_login.py -t 10.135.7.130 -p data.mdb
[*] Successfully extracted the IdP certificate
Traceback (most recent call last):
  File "vcenter_saml_login.py", line 311, in <module>
    trusted_cert_1, domain = get_trusted_cert1(bin_stream, args.verbose)
TypeError: cannot unpack non-iterable NoneType object

**Comment by scopedsecurity** [comment]
I've pushed an update that should solve the issues
