### ISSUE TITLE
vcenter 6.7 for windows not work

### ISSUE THREAD

**Issue by L-codes** [horizon3ai/vcenter_saml_login#4]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/20529064/147238172-5b9905ee-7cfa-453d-9213-cdea35594159.png">

**Comment by scopedsecurity** [comment]
Hi,

Do you have any more information about the set up of this vCenter instance? I had tried it on a Windows vCenter instance that was 6.7 a few months back and it seemed to work fine. If you obtained a valid session ID I'm not sure what could be wrong.

When setting the session Cookie in the browser be sure to apply it to the /ui path and then re-browse to the host with the /ui path set in the URL.

**Comment by L-codes** [comment]
Yes, that’s how I do it, but I can’t get the cookie

I will close the issue first and open it again when there is more information
